# Задача восстановления пропусков

Список исходных переменных включает в себя:  
- State -- штат
- Account_length -- длина счета 
- Code -- код
- Phone_number -- номер телефона
- International_calls -- международные звонки 
- Voice_mail -- голосовая почта 
- Number_of_voicemails -- количество голосовых сообщений 
- Daytime_minutes_used -- использовано дневных минут
- Number_of_calls_during_the_day -- количество звонков днем
- Monthly fee -- абонентская плата днем
- Used_evening_minutes -- использовано вечерних минут
- Number_of_calls_in_the_evening -- количество звонков вечером
- Subscription_fee_in_the_evening -- абонентская плата вечером 
- Using_night_minutes -- использование ночных минут  
- Number_of_night_calls -- количество ночных звонков
- Nightly_subscription_fee -- абонентская плата ночью
- Minutes_of_long_distance_calls -- минут междугородних разговоров
- Number_of_international_calls -- число международных звонков
- Subscription_fee_for_international_calls -- абонентская плата за международные звонки 
- The_number_of_calls_to_the_service_department -- число обращений в сервисную службу 
- Care -- уход (целевой показатель)

In [5]:
import pandas as pd   #загрузка библиотеки pandas. Эта конструкция используется для сокращения имени библиотеки.

In [10]:
pd.set_option('display.precision',3) #количество отображаемых знаков после запятой
df=pd.read_excel('churn.xls', sheet_name='churn_missing') #чтение исходных данных из Excel-файла churn.xls с рабочего листа churn

Определение размерности массива с помощью свойства `.shape`

In [16]:
df.shape

(3333, 21)

Просмотр заголовков массива с помощью свойства `.columns`

In [17]:
df.columns

Index(['State', 'Account_length', 'Code', 'Phone_number',
       'International_calls', 'Voice_mail', 'Number_of_voicemails',
       'Daytime_minutes_used', 'Number_of_calls_during_the_day', 'Monthly fee',
       'Used_evening_minutes', 'Number_of_calls_in_the_evening',
       'Subscription_fee_in_the_evening', 'Using_night_minutes',
       'Number_of_night_calls', 'Nightly_subscription_fee',
       'Minutes_of_long_distance_calls', 'Number_of_international_calls',
       'Subscription_fee_for_international_calls',
       'The_number_of_calls_to_the_service_department', 'Care'],
      dtype='object')

Просмотр пяти начальных строк массива с помощью свойства `.head()`. Просмотр последних строк обеспечивается свойством `.tail()`

In [21]:
df.head()

,State,Account_length,Code,Phone_number,International_calls,Voice_mail,Number_of_voicemails,Daytime_minutes_used,Number_of_calls_during_the_day,Monthly fee,...,Number_of_calls_in_the_evening,Subscription_fee_in_the_evening,Using_night_minutes,Number_of_night_calls,Nightly_subscription_fee,Minutes_of_long_distance_calls,Number_of_international_calls,Subscription_fee_for_international_calls,The_number_of_calls_to_the_service_department,Care
0,KS,128.0,415,382-4657,нет,да,25,265.1,110.0,45.07,...,99,16.78,244.7,91.0,11.01,10.0,3,2.70,1,Нет
1,OH,107.0,415,371-7191,нет,да,26,161.6,123.0,27.47,...,103,16.62,254.4,103.0,11.45,13.7,3,3.70,1,Нет
2,NJ,137.0,415,358-1921,нет,нет,0,243.4,114.0,41.38,...,110,10.30,162.6,104.0,7.32,12.2,5,3.29,0,Нет
3,OH,84.0,408,375-9999,да,нет,0,299.4,71.0,50.90,...,88,5.26,196.9,89.0,8.86,6.6,7,1.78,2,Нет
4,OK,75.0,415,330-6626,да,нет,0,166.7,113.0,28.34,...,122,12.61,186.9,121.0,8.41,10.1,3,2.73,3,Нет

Информацию о типах переменных можно узнать с помощью метода `.info()`

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 21 columns):
State                                            3331 non-null object
Account_length                                   3332 non-null float64
Code                                             3333 non-null int64
Phone_number                                     3331 non-null object
International_calls                              3331 non-null object
Voice_mail                                       3330 non-null object
Number_of_voicemails                             3333 non-null int64
Daytime_minutes_used                             3332 non-null float64
Number_of_calls_during_the_day                   3332 non-null float64
Monthly fee                                      3331 non-null float64
Used_evening_minutes                             3333 non-null float64
Number_of_calls_in_the_evening                   3333 non-null int64
Subscription_fee_in_the_evening                  3333 non-null float64
Using_night_minutes                              3332 non-null float64
Number_of_night_calls                            3332 non-null float64
Nightly_subscription_fee                         3332 non-null float64
Minutes_of_long_distance_calls                   3333 non-null float64
Number_of_international_calls                    3333 non-null int64
Subscription_fee_for_international_calls         3332 non-null float64
The_number_of_calls_to_the_service_department    3333 non-null int64
Care                                             3333 non-null object
dtypes: float64(11), int64(5), object(5)
memory usage: 546.9+ KB

Имеем: State, Phone_number, International_calls, Voice_mail, Care --- категориальные переменные (тип `object`), остальные переменные --- количественные.

Находим частоты значений исследуемых переменных с помощью метода `.value_counts()`. При необходимости редкие значения переменной объединяются в одно значение

In [23]:
set_columns=[c for c in df.columns] 
for c in set_columns:
    print(df[c].value_counts())

WV    106
NY     83
MN     83
AL     80
OR     78
WI     78
OH     78
WY     77
VA     77
CT     74
ID     73
MI     73
VT     73
UT     72
TX     71
IN     71
MD     70
KS     70
NC     68
MT     68
NJ     68
WA     66
CO     66
NV     66
MA     65
MS     65
RI     65
AZ     64
MO     63
FL     63
ME     62
NM     62
ND     62
OK     61
NE     61
DE     61
SC     60
SD     60
KY     59
IL     58
NH     56
AR     55
GA     54
DC     54
HI     53
TN     53
AK     52
LA     51
PA     45
IA     44
CA     34
Name: State, dtype: int64
105.0    43
87.0     42
93.0     40
101.0    40
90.0     39
         ..
200.0     1
199.0     1
202.0     1
188.0     1
5.0       1
Name: Account_length, Length: 212, dtype: int64
415    1655
510     840
408     838
Name: Code, dtype: int64
394-9220    1
383-4641    1
337-7739    1
373-1028    1
385-7688    1
           ..
371-3498    1
345-8433    1
401-3077    1
348-3581    1
338-8050    1
Name: Phone_number, Length: 3331, dtype: int64
нет    3009
да      322
Name: International_calls, dtype: int64
нет    2409
да      921
Name: Voice_mail, dtype: int64
0     2411
31      60
29      53
28      51
33      46
27      44
30      44
24      42
26      41
32      41
25      37
23      36
36      34
35      32
22      32
39      30
37      29
34      29
21      28
38      25
20      22
19      19
40      16
42      15
17      14
41      13
16      13
43       9
15       9
18       7
44       7
14       7
45       6
12       6
46       4
13       4
47       3
8        2
48       2
50       2
9        2
11       2
49       1
10       1
4        1
51       1
Name: Number_of_voicemails, dtype: int64
174.5    8
154.0    8
159.5    8
175.4    7
162.3    7
        ..
199.9    1
125.6    1
105.8    1
88.1     1
270.8    1
Name: Daytime_minutes_used, Length: 1666, dtype: int64
102.0    78
105.0    75
95.0     69
107.0    69
104.0    68
         ..
149.0     1
165.0     1
36.0      1
157.0     1
152.0     1
Name: Number_of_calls_during_the_day, Length: 119, dtype: int64
27.12    8
29.67    8
26.18    8
29.82    7
31.18    7
        ..
47.24    1
20.67    1
16.95    1
34.12    1
13.28    1
Name: Monthly fee, Length: 1666, dtype: int64
169.9    9
230.9    7
209.4    7
201.0    7
220.6    7
        ..
335.0    1
258.9    1
134.7    1
318.8    1
317.2    1
Name: Used_evening_minutes, Length: 1611, dtype: int64
105    80
94     79
108    71
97     70
102    70
       ..
45      1
49      1
145     1
153     1
0       1
Name: Number_of_calls_in_the_evening, Length: 123, dtype: int64
14.25    11
16.12    11
15.90    10
18.62     9
14.44     9
         ..
12.64     1
13.83     1
11.39     1
28.03     1
20.53     1
Name: Subscription_fee_in_the_evening, Length: 1440, dtype: int64
197.4    8
214.6    8
188.2    8
210.0    8
191.4    8
        ..
235.7    1
258.5    1
155.3    1
94.1     1
182.6    1
Name: Using_night_minutes, Length: 1590, dtype: int64
105.0    84
104.0    77
91.0     76
102.0    72
106.0    69
         ..
166.0     1
38.0      1
36.0      1
48.0      1
149.0     1
Name: Number_of_night_calls, Length: 120, dtype: int64
9.45     15
9.66     15
8.88     14
8.47     14
7.69     13
         ..
11.71     1
5.74      1
13.42     1
13.14     1
6.14      1
Name: Nightly_subscription_fee, Length: 933, dtype: int64
10.0    62
11.3    59
9.8     56
10.9    56
10.1    53
        ..
18.9     1
1.3      1
2.7      1
2.6      1
3.1      1
Name: Minutes_of_long_distance_calls, Length: 162, dtype: int64
3     668
4     619
2     489
5     472
6     336
7     218
1     160
8     116
9     109
10     50
11     28
0      18
12     15
13     14
15      7
14      6
18      3
16      2
19      1
17      1
20      1
Name: Number_of_international_calls, dtype: int64
2.70    62
3.05    59
2.65    56
2.94    56
2.73    53
        ..
0.68     1
4.83     1
0.84     1
0.30     1
5.40     1
Name: Subscription_fee_for_international_calls, Length: 162, dtype: int64
1    1181
2     759
0     697
3     429
4     166
5      66
6      22
7       9
9       2
8       2
Name: The_number_of_calls_to_the_service_department, dtype: int64
Нет    2850
Да      483
Name: Care, dtype: int64

Исследуем данные переменные на наличие пропусков. Для этого воспользуемся методом `.value_counts()` со значением параметра `dropna=False`

In [25]:
for c in set_columns:
    print(df[c].value_counts(dropna=False))

WV     106
NY      83
MN      83
AL      80
OR      78
OH      78
WI      78
WY      77
VA      77
CT      74
ID      73
VT      73
MI      73
UT      72
IN      71
TX      71
MD      70
KS      70
NJ      68
NC      68
MT      68
CO      66
NV      66
WA      66
RI      65
MA      65
MS      65
AZ      64
MO      63
FL      63
ME      62
ND      62
NM      62
OK      61
DE      61
NE      61
SC      60
SD      60
KY      59
IL      58
NH      56
AR      55
GA      54
DC      54
TN      53
HI      53
AK      52
LA      51
PA      45
IA      44
CA      34
NaN      2
Name: State, dtype: int64
105.0    43
87.0     42
93.0     40
101.0    40
90.0     39
         ..
188.0     1
4.0       1
243.0     1
208.0     1
221.0     1
Name: Account_length, Length: 213, dtype: int64
415    1655
510     840
408     838
Name: Code, dtype: int64
NaN         2
389-5988    1
373-1028    1
385-7688    1
378-4145    1
           ..
371-3498    1
345-8433    1
401-3077    1
348-3581    1
395-8595    1
Name: Phone_number, Length: 3332, dtype: int64
нет    3009
да      322
NaN       2
Name: International_calls, dtype: int64
нет    2409
да      921
NaN       3
Name: Voice_mail, dtype: int64
0     2411
31      60
29      53
28      51
33      46
27      44
30      44
24      42
26      41
32      41
25      37
23      36
36      34
35      32
22      32
39      30
37      29
34      29
21      28
38      25
20      22
19      19
40      16
42      15
17      14
41      13
16      13
43       9
15       9
18       7
44       7
14       7
45       6
12       6
46       4
13       4
47       3
8        2
48       2
50       2
9        2
11       2
49       1
10       1
4        1
51       1
Name: Number_of_voicemails, dtype: int64
174.5    8
154.0    8
159.5    8
175.4    7
162.3    7
        ..
199.9    1
125.6    1
105.8    1
88.1     1
44.9     1
Name: Daytime_minutes_used, Length: 1667, dtype: int64
102.0    78
105.0    75
95.0     69
107.0    69
104.0    68
         ..
152.0     1
35.0      1
156.0     1
NaN       1
160.0     1
Name: Number_of_calls_during_the_day, Length: 120, dtype: int64
26.18    8
27.12    8
29.67    8
29.82    7
31.18    7
        ..
23.94    1
27.39    1
14.79    1
46.48    1
13.28    1
Name: Monthly fee, Length: 1667, dtype: int64
169.9    9
230.9    7
209.4    7
201.0    7
220.6    7
        ..
335.0    1
258.9    1
134.7    1
318.8    1
317.2    1
Name: Used_evening_minutes, Length: 1611, dtype: int64
105    80
94     79
108    71
97     70
102    70
       ..
45      1
49      1
145     1
153     1
0       1
Name: Number_of_calls_in_the_evening, Length: 123, dtype: int64
14.25    11
16.12    11
15.90    10
18.62     9
14.44     9
         ..
12.64     1
13.83     1
11.39     1
28.03     1
20.53     1
Name: Subscription_fee_in_the_evening, Length: 1440, dtype: int64
197.4    8
214.6    8
188.2    8
210.0    8
191.4    8
        ..
235.7    1
258.5    1
155.3    1
94.1     1
182.6    1
Name: Using_night_minutes, Length: 1591, dtype: int64
105.0    84
104.0    77
91.0     76
102.0    72
106.0    69
         ..
48.0      1
158.0     1
44.0      1
38.0      1
36.0      1
Name: Number_of_night_calls, Length: 121, dtype: int64
9.66     15
9.45     15
8.47     14
8.88     14
7.69     13
         ..
3.41      1
14.04     1
12.75     1
13.75     1
3.20      1
Name: Nightly_subscription_fee, Length: 934, dtype: int64
10.0    62
11.3    59
9.8     56
10.9    56
10.1    53
        ..
18.9     1
1.3      1
2.7      1
2.6      1
3.1      1
Name: Minutes_of_long_distance_calls, Length: 162, dtype: int64
3     668
4     619
2     489
5     472
6     336
7     218
1     160
8     116
9     109
10     50
11     28
0      18
12     15
13     14
15      7
14      6
18      3
16      2
19      1
17      1
20      1
Name: Number_of_international_calls, dtype: int64
2.70    62
3.05    59
2.65    56
2.94    56
2.73    53
        ..
0.70     1
0.35     1
0.73     1
4.83     1
5.10     1
Name: Subscription_fee_for_international_calls, Length: 163, dtype: int64
1    1181
2     759
0     697
3     429
4     166
5      66
6      22
7       9
9       2
8       2
Name: The_number_of_calls_to_the_service_department, dtype: int64
Нет    2850
Да      483
Name: Care, dtype: int64

Вывод общей информации о наличие пропусков во всех переменных можно осуществить, воспользовавшись цепочкой методов `.isnull()` и `.sum()`

In [27]:
df.isnull().sum()

State                                            2
Account_length                                   1
Code                                             0
Phone_number                                     2
International_calls                              2
Voice_mail                                       3
Number_of_voicemails                             0
Daytime_minutes_used                             1
Number_of_calls_during_the_day                   1
Monthly fee                                      2
Used_evening_minutes                             0
Number_of_calls_in_the_evening                   0
Subscription_fee_in_the_evening                  0
Using_night_minutes                              1
Number_of_night_calls                            1
Nightly_subscription_fee                         1
Minutes_of_long_distance_calls                   0
Number_of_international_calls                    0
Subscription_fee_for_international_calls         1
The_number_of_calls_to_the_service_department    0
Care                                             0
dtype: int64

Видим наличие пропусков в исследуемых данных

**Заполнение пропусков количественных переменных**  
Пропуски в количественных переменных заполняются значениями вычисленных статистик: среднее, мода. Пропуски также можно заменять константами. 
Для замены пропущенных значений воспользуемся методом `.fillna()` с параметром `inplace` равным `True` для выполнения замены на месте.
Нижеследующий код заполяет пропуски по переменным, перечисленным в списке.

In [29]:
for i in ['Daytime_minutes_used', 'Number_of_calls_during_the_day', 'Monthly fee', 'Using_night_minutes', 'Number_of_night_calls', 'Nightly_subscription_fee', 'Subscription_fee_for_international_calls']:
    if i in df.columns:
        df[i].fillna(df[i].mean(), inplace=True)

ДОПОЛНИТЕЛЬНАЯ ИНФОРМАЦИЯ  
Если необходимо заполнить пробелы по одному признаку, то   
    `df['признак'].fillna(df['признак'].mean(), inplace=True)`

In [33]:
df.isnull().sum()

State                                            2
Account_length                                   0
Code                                             0
Phone_number                                     2
International_calls                              2
Voice_mail                                       3
Number_of_voicemails                             0
Daytime_minutes_used                             0
Number_of_calls_during_the_day                   0
Monthly fee                                      0
Used_evening_minutes                             0
Number_of_calls_in_the_evening                   0
Subscription_fee_in_the_evening                  0
Using_night_minutes                              0
Number_of_night_calls                            0
Nightly_subscription_fee                         0
Minutes_of_long_distance_calls                   0
Number_of_international_calls                    0
Subscription_fee_for_international_calls         0
The_number_of_calls_to_the_service_department    0
Care                                             0
dtype: int64

Пропусков в количественных переменных нет.

В данном случае пропущенные значения замещены выборочным средним `.mean()`. Для замены пропущенных значений медианой следует воспользоваться `.median()`.  
Если же пропущенное значение `принака` необходимо заменить `константой`, то  
`df['признак'].fillna(константа, inplace=True)`

Сохранение датафрейма в csv-файл с помощью метода `.to_csv()`

In [34]:
df.to_csv('call_client.csv')